### ISSUE TITLE
How to get started with this sample?

### ISSUE THREAD

**Issue by benedekh** [Yakindu/playgo#1]
Dear All,

I have been experimenting with PlayGo, and I came across with this Yakindu -> PlayGo code generator. Could you give me any help, how to get started with the generated code? 

The following interfaces / classes cannot be resolved either in PlayGo or in the other Eclipse where Yakindu Statecharts is installed:
- il.ac.wis.cs.playgo.ee.sct.IExecutionEngineSCT
- il.ac.wis.cs.playgo.playtoolkit.ebridge.IExecutionBridge
- il.ac.wis.cs.playgo.ee.sct.ExecutionBridge2SCT

As far as I see the example might be in an early alpha phase, and a lot of integration code has to be generated to make PlayGo play-out the statechart. Could you tell me, how far I am from the reality?

Thank you for help.

Regards,
Ben

**Comment by smadarsz** [comment]
Hello Ben,

Indeed we are working on integrated execution of LSCs and Statecharts.
This is a work in progress, done in Prof. David Harel lab (who is the
inventor of both LSC and Statechart).
Although we are in advance phase of the research, we haven't completed it
yet, and so we did not publish yet a PlayGo version that supports the
integration.

Should you have questions about it, feel free to send me.

Best,
Smadar

**Comment by benedekh** [comment]
Dear Smadar,

Thank you for the reply. May I have further questions regarding statecharts (SCT) integration with LSC?

What kind of integration are you working on?
- SCT and LSC bisimulation;
- authomatic SCT synthesis from LSC;
- generating LSC from SCT.

How mature is the progress? Is there any publication available regarding the process or the results already achieved? I have read many publications from Prof. David Harel regarding LSC semantics, authomatic SCT synthesis from LSC, and so on.

If some pieces of these information are not public yet, or may not be discussed on GitHub, please contact me at ![](http://home.sch.bme.hu/~benjo123/sm/email2.png).

Thank you.

Best regards,
Benedek

**Comment by smadarsz** [comment]
Hi again,

The integration we work on is the first one on your list: an integrated
execution of a project or application that is comprised of LSCs and
Statecharts.
By the way, it is currently based on Java code, so it can be viewed as more
then a simulation, in terms that it can be executed outside the context of
PlayGo.

We already have a working implementation of the semantics we defined.
However, there is no publication yet...

Please let me know if you have further questions.

Best,
Smadar
